---

# Restart selenium to work around its memory leakage issues
# TODO: is this really needed?
- name: restart selenium
  systemd:
    name: selenium-server
    state: restarted

- name: start ytestrunner2
  systemd:
    name: ytestrunner2
    state: started
    enabled: true
    daemon_reload: true
  become: true

# TODO: Some additional healthcheck to be implemented to verify that application is working & healthy
- name: Wait until yTR port becomes accessable
  wait_for:
    port: "{{port_ytr}}"
    delay: 5
    sleep: 1
    timeout: 90