---
# defaults file for jenkins

jenkins_java_opts: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
jenkins_groovy_dir: "/var/lib/jenkins/init.groovy.d"

jenkins_groovy_ad:
  - "00_proxy_configuration.groovy.j2"
  - "60_active_directory.groovy.j2"
  - "61_role_based_auth.groovy.j2"

jenkins_project_roles:
#  This should be defined in the group_vars with datacenter-specific settings
#  The content is:
#
#  role_name:
#    acl_name: "ACL-{{dc.ID}}-CMZJENKINS-SOMETHING"
#    pattern: "^SOMETHING.*"
#

jvm_keystore_path: "/usr/java/latest/jre/lib/security/cacerts"

ssl_enable: "yes"
ssl_cert_privkey_path: "/etc/ssl/private/jenkins.key"
ssl_cert_csr_path: "/etc/ssl/private/jenkins.csr"
ssl_cert_cert_path: "/etc/ssl/private/jenkins.pem"

ssl_cert_country: "''"
ssl_cert_locality: "''''"
ssl_cert_organization: "'SAP Hybris SRE'"
ssl_cert_state: "''"
ssl_cert_common_name: "{{ansible_fqdn}}"
ssl_cert_days: "365"
ssl_cert_fields: "/C={{ssl_cert_country}}/ST={{ssl_cert_state}}/L={{ssl_cert_locality}}/O={{ssl_cert_organization}}/CN={{ssl_cert_common_name}}"
