---

loadbalancer: mo2-cmz-webpvip-001.ycommerce.ycs.io

loadbalanced_url:
  rdk:
    fqdn: mo2-rdk-p.ycommerce.ycs.io
  por:
    fqdn: mo2-por-p.ycommerce.ycs.io
  ytr:
    fqdn: mo2-ytr-p.ycommerce.ycs.io
  repo:
    fqdn: mo2-repo-p.ycommerce.ycs.io
  ctrl:
    fqdn: mo2-ctrl-p.ycommerce.ycs.io

ytr_nfs_server: mo2-cmz-ytrpst-001.ycommerce.ycs.io
rdk_nfs_server: mo2-cmz-rdkpst-001.ycommerce.ycs.io

cmdbadaptor_spring_datasource_url: jdbc:mysql://mo2-cmz-cmdbp-001.ycommerce.ycs.io:3306/portal_001?useUnicode=true&amp;characterEncoding=UTF-8

middleware_portal_server_address: http://{{ansible_fqdn}}:8080

middleware_rundeck_outbound_server_address: https://mo2-cmz-rdkp-001.ycommerce.ycs.io:4443
