---

- name: Check if we need to install MySQL client
  command: "rpm -q MySQL-client-5.5.57"
  register: install_mysql_client
  ignore_errors: true
  failed_when: false
  changed_when: false

- block:
  # get the mysql packages from the repo server
  - include: "mysql_packages.yml"
    static: true

  - name: Select rpms for mysql client installation
    shell: cp MySQL-{{item}}-*.rpm  client_rpms
    with_items:
      - client
      - devel
      - shared
      - shared-compat
    args:
      chdir: /tmp/ansible_tempdir/mysql

  # To ensure correct order of installtion we need to install with the asterics (*)
  # This is why we cannot go for the package or yum module.
  - name: Install MySQL client
    shell: yum install -y /tmp/ansible_tempdir/mysql/client_rpms/MySQL-*.rpm
  when: install_mysql_client.rc != 0

