---

rev_proxy_config_backend:
  rdk:
    backend_inventory_group: Rundeck
    backend_protocol: "{{protocol_rdk}}"
    backend_port: "{{port_rdk}}"
    sticky_session: true
  por:
    backend_inventory_group: Portal
    backend_protocol: "{{protocol_por}}"
    backend_port: "{{port_por}}"
    sticky_session: true
  ytr:
    backend_inventory_group: yTestRunner
    backend_protocol: "{{protocol_ytr}}"
    backend_port: "{{port_ytr}}"
    sticky_session: true
  repo:
    backend_inventory_group: Repo
    backend_protocol: "{{protocol_repo}}"
    backend_port: "{{port_repo}}"
    sticky_session: false
