---

- hosts: Portal

  become: true

  vars_files:
    - roles/PortalDeployment/defaults/main.yml

  roles:
    - {
        role: PortalDeployment,
        deployment_vars: "{{automationportal}}",
        tags: deploy_automationportal
      }
